[tasks.BUILD]
description = "Build r9cc"
script = ['''
#!/usr/bin/env bash
cargo build
''']

[tasks.TEST]
description = "Test hoge"
script = ['''
#!/usr/bin/env bash
assert() {
    expected="$1"
    input="$2"

    ./target/debug/r9cc $input > tmp.s
    cc -o tmp tmp.s
    ./tmp
    actual="$?"

    if [ "$actual" = "$expected" ]; then
        echo "$input => $actual"
    else
        echo "$input => $expected expected, but got $actual"
        exit 1
    fi
}


assert 0 0
assert 42 42

echo OK
exit 0
''']

dependencies = ["BUILD"]
